# Generated by Django 5.2.2 on 2025-06-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
