# Generated by Django 5.2.2 on 2025-06-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task3', '0002_alter_appuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
