# Generated by Django 5.2.2 on 2025-06-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task3', '0003_alter_appuser_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
